# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: apex_development

test:
  <<: *default
  database: apex_test

production:
  primary: &primary_production
    <<: *default
    database: apex_production
    username: apex
    password: <%= ENV["APEX_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: apex_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: apex_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: apex_production_cable
    migrations_paths: db/cable_migrate
