default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch('DB_USER', 'admin') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'admin') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'apex_development') %>  # <-- Use DB_NAME aqui

test:
  <<: *default
  database: apex_test

production_local:
  primary:
    <<: *default
    database: <%= ENV.fetch('PROD_DB_NAME', 'apex_production') %>

  cache:
    <<: *default
    database: <%= ENV.fetch('CACHE_DB_NAME', 'apex_cache') %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV.fetch('QUEUE_DB_NAME', 'apex_queue') %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV.fetch('CABLE_DB_NAME', 'apex_cable') %>
    migrations_paths: db/cable_migrate

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate